### ISSUE TITLE
Problem with active tabs

### ISSUE THREAD

**Issue by betel98** [jenstornell/tabbis.js#21]
I want only the tabs(divs) on my current path to be set as "active". Can i achieve this with the new version?

**Comment by jenstornell** [comment]
I'm not sure what you mean. In the old version you could set `class="active"` class on the tabs to make it active. In the new version you instead need to set `data-active` to make that work.

If this does not solve your problem, maybe add a screenshot to make it clear what is your issue.

**Comment by jenstornell** [comment]
I've released version 3.0 already and it should solve your problem.

**Comment by jenstornell** [comment]
https://github.com/jenstornell/tabbis.js#active-tab

If you don't want a tab to be active automatically:

```js
tabActiveFallback: false
```

If you want to enable memory:

```js
memory: true
```
