### ISSUE TITLE
Any way to move tabs to another row when resizing window? 

### ISSUE THREAD

**Issue by PrzemyslawKlys** [jenstornell/tabbis.js#8]
Is there a way for tabs to resize so that when there are too many tabs those would go to another row?

**Comment by jenstornell** [comment]
You mean in the stylesheet? I may be looking into it for the new version coming soon, I hope.

**Comment by PrzemyslawKlys** [comment]
I actually modified your tabbis.js a bit because of issues for IE used locally - https://github.com/EvotecIT/PSWriteHTML/blob/master/Resources/JS/tabbis.js

As for your question - yes. Right now it doesn't span to another row if there's no place. It looks ugly.

**Comment by jenstornell** [comment]
@PrzemyslawKlys I looked into your code. Nice work! It looks like the problems with IE has to do with local storage. I will continue to not support IE in my next version because it's old and would require more code.

**Comment by PrzemyslawKlys** [comment]
It's your choice, but for a lot of companies, it's still no go. I understand tho. 

I do appreciate your work. I modified CSS for it and use it in PSWriteHTML module.

![image](https://user-images.githubusercontent.com/15063294/74090628-e0d3dc80-4aad-11ea-8ded-39a75fb2d8a0.png)

![image](https://user-images.githubusercontent.com/15063294/74090632-edf0cb80-4aad-11ea-9654-930453172514.png)

![image](https://user-images.githubusercontent.com/15063294/74090635-fd701480-4aad-11ea-9d01-2724a8999527.png)

![image](https://user-images.githubusercontent.com/15063294/74090642-0bbe3080-4aae-11ea-930b-26c71137087a.png)

If you want to take a look here are the examples: https://github.com/EvotecIT/PSWriteHTML/tree/master/Examples/Example22-Tabs

**Comment by jenstornell** [comment]
@PrzemyslawKlys Alright. I've changed my mind a bit.

I will release two versions, an old one similar to the current one and one ES6 version. I use a lot of new ES6 stuff in my new version. That way it will be much more readable, shorter and will perform better.

**Comment by jenstornell** [comment]
@PrzemyslawKlys Can I use your IE fixes in my "old" version? Might be helpful for IE users.

**Comment by PrzemyslawKlys** [comment]
Of course!

**Comment by jenstornell** [comment]
I've uploaded a new version now, a complete rewrite (without IE support). I've not yet implemented your IE fixes for the old code.

I have made a fix for tabs when they don't fit on the screen. It's not what you was asking for, the do not jump down to a new row. Instead I use `overflow-x: scroll` which means that we can scroll to see the rest. It's a common mobile pattern.

If you want to know more about the new version, see the changelog:
https://github.com/jenstornell/tabbis.js/blob/master/CHANGELOG.md

If you want to reply to this, feel free to do so, but I'm closing this issue now.

**Comment by PrzemyslawKlys** [comment]
Thank you. I'll probably have to try and add IE support for it if it's even possible :-) My users often run PSWriteHTML on servers and IE is still the only browser on it. It's not your problem tho :-) Again thanks for your work. It allowed me to expand on PSWriteHTML with multiple tabs with no effort.

**Comment by jenstornell** [comment]
@PrzemyslawKlys Thanks!

Maybe you should save your time not trying to make the new version IE friendly, because there are so many new things in there. It's supported by modern browsers, even Edge but not IE.

**Of the top of my head:**

- Classes - https://caniuse.com/#feat=es6-class
- Arrow functions - https://caniuse.com/#feat=arrow-functions
- Spread syntax - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Browser_compatibility
- Object values - https://caniuse.com/#feat=object-values
- Local storage - You know about that one

There may be even more things.

If you still want to try, I wish you luck!

**Comment by PrzemyslawKlys** [comment]
Ye, I may just leave what I have and let it run for some time. But with that being said I will never be able to switch to new version if I want to support my community. Microsoft still hasn't removed, depreciated IE from servers even for Windows 2016/Windows 2019 so it will take years before I can switch. 

Maybe I'll have PSWriteHTML and PSWriteHTMLv2 with no IE support ;)

**Comment by jenstornell** [comment]
@PrzemyslawKlys Alright. Edge came out 5 years ago, but I think they integrated IE deep into the core of Windows and therefor it's hard for them to get rid of.

The old version of Tabbis will still work, maybe forever and does not rely on security so I think you can just go with the old one as long as it works well for you.

**Comment by jenstornell** [comment]
@PrzemyslawKlys Hello again!

I've managed to convert the ES6 version to ES5 which should work with IE11. 😄 I will not take the credit, it's all the work by [Babel](https://babeljs.io/repl).

https://github.com/jenstornell/tabbis.js/blob/master/assets/js/dist/tabbis.es5.min.js

Also I've gone from version 2.0 to version 3.0 in just one week. You can read all about it in the changelog.

https://github.com/jenstornell/tabbis.js/blob/master/docs/CHANGELOG.md

If you would like to try it out in IE11, it would help me to know if it works. Be aware that the syntax may have changed a little.

**Comment by PrzemyslawKlys** [comment]
Great! Thank you. Will do the testing!

**Comment by jenstornell** [comment]
Maybe even simpler would be to test the demo:

https://csspoo.com/tabbis/examples/simple.html

Also for testing purposed it may be easier to use the non compressed version:

https://github.com/jenstornell/tabbis.js/blob/master/assets/js/dist/tabbis.es5.js

**Comment by PrzemyslawKlys** [comment]
Demo didn't work on IE

![image](https://user-images.githubusercontent.com/15063294/74734768-8544e400-524f-11ea-9620-2409c0603817.png)

**Comment by jenstornell** [comment]
@PrzemyslawKlys Crap! Thanks for trying it out anyway.

**Comment by PrzemyslawKlys** [comment]
![image](https://user-images.githubusercontent.com/15063294/74735251-92ae9e00-5250-11ea-81bf-761b91724c99.png)

**Comment by jenstornell** [comment]
@PrzemyslawKlys I see. Babel does not convert Object.assign to a IE11 friendly syntax. Even if I could fix it, the CSS would probably be a nightmare to fix. I see that display flex is not supported and not even styling of buttons.

I think I will give up again, at least for now.

Thanks again!

**Comment by PrzemyslawKlys** [comment]
CSS seems to work on the old version? And it uses flex no? I also use flex all over the place.

![image](https://user-images.githubusercontent.com/15063294/74736639-7d873e80-5253-11ea-85b8-2febb29ed5c3.png)

In IE:

![image](https://user-images.githubusercontent.com/15063294/74736701-9d1e6700-5253-11ea-9544-7fac7bca4c1a.png)

I am JS/HTML/CSS noob so possibly mixing up things.

**Comment by jenstornell** [comment]
@PrzemyslawKlys Yes, you are right. I'll blame the flu that I have.

It's the `hidden` that is not supported and that would actually be easy to fix for IE11 `[hidden] { display: none }`.

If I make it work, I think I need an IE11 example/demo and change the buttons to divs. It's less semantic and not as recommended but would work much better for styling. The ES5 version would not change, just the HTML.
